name = "pointybubl"
license = "MIT"
licenselink = "https://github.com/pointyfar/pointybubl/blob/master/LICENSE.md"
description = "BUBL: A Bulma Blog theme for Hugo. Configurable sidebar boxes and list layouts."
homepage = "https://pointy.netlify.com/"
tags = ["blog", "bulma", "page bundles", "food", "photography", "images", "print-friendly" ]
features = ["page bundles", "image gallery", "Hugo pipes"]
min_version = "0.53"

[author]
  name = "PointyFar"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
