baseURL = "/"
languageCode = "en-us"
title = "Pointy's"

# Only use if exampleSite is inside theme folder
themesDir = "../../"

theme = "pointybubl"
paginate = 8

pygmentsUseClassic = false
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

#sectionPagesMenu = "main"
    
[[menu.main]]
  name = "Attributions"
  title = "Attributions"
  weight = 100
  identifier = "attributions"
  url = "/attributions/"

[[menu.main]]
  name = "About"
  title = "About the Author"
  weight = 110
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Recipes"
  title = "Recipes and Food Section"
  weight = 120
  identifier = "food"
  url = "/food/"

[[menu.main]]
    name = "Lorem"
    title = "Lorem Ipsum"
    weight = 130
    identifier = "lorem"
    url = "/lorem/"

[params]
  copyright = "© 2018 PointyFar"
  subtitle = "Blog Template for Hugo"
  mainSections = ["food", "post", "wonderland"]
  
  socialdata = "social"

[params.search]
  enabled = true
  icon = true
  label = "fas fa-search"
  
[params.placeholder]
  #disabled = true
  ## use img 
  _img = "/img/placeholder-100.png"
  
  ## use svg
  size = "100px"
  text = "[no image available]"
  text_size = "9px"
  authorsTaxonomy = "authors"
  
[params.scss]
  customFontBody = "Georgia,Utopia,Charter,serif"
  brandFont = "'Oswald', sans-serif"
  primary = "CadetBlue"
  primaryInvert = "#fff"
  
  footnote = "FOOTNOTE:"
  
[params.hero]
  #background = "img/hero-background.jpeg"
  background = "img/hero-background-dark.jpeg"
  #background = "img/hero-background-light.jpeg"
  bgislight = false

[[params.authors]]
  name = "default-author"
  default = true
  
[[params.authors]]
  name = "pointy-far"
  featured = true

[params.subnav]
  usetaxonomy = "authors"
  taxonomycount = 3
  featuredterms = ["me"]
  
  
  
[params.footer]
  left = ["footerlinks", "otherlinks", "footerlinks"]
  right = ["copyright", "footertext", "footerimage"]
  

[[params.display_taxonomies]]
  position = "head"
  name = "cuisine"
  labeled = true
  
[[params.display_taxonomies]]
  position = "head"
  name = "tags"
  style = "list"
  labeled = true
  label = "Tags: "

[[params.display_taxonomies]]
  position = "head"
  name = "difficulty"
  labeled = true
  label = "Difficulty: "

[[params.display_taxonomies]]
  position = "foot"
  name = "categories"
  labeled = true
  label = "Categorised: "

  
[taxonomies]
  category = "categories"
  tag = "tags"
  difficulty = "difficulty"
  cuisine = "cuisine"
  author = "authors"
  
[outputs]
  home = ["HTML", "JSON"]