baseURL = "/"
languageCode = "en-us"
title = "Pointy's"

# Only use if exampleSite is inside theme folder
themesDir = "../../"

theme = "pointybubl"
paginate = 8

#sectionPagesMenu = "main"

[[menu.main]]
  name = "Attributions"
  title = "Attributions"
  weight = 100
  identifier = "attributions"
  url = "/attributions/"

[[menu.main]]
  name = "About"
  title = "About the Author"
  weight = 110
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Recipes"
  title = "Recipes and Food Section"
  weight = 120
  identifier = "food"
  url = "/food/"

[[menu.main]]
    name = "Lorem"
    title = "Lorem Ipsum"
    weight = 130
    identifier = "lorem"
    url = "/lorem/"

[params]
  copyright = "© 2018 PointyFar"
  subtitle = "Blog Template for Hugo"
  mainSections = ["food", "post", "wonderland"]
  
  _socialdata = "social"
  usePipes = true   ## setting to false DOES NOT WORK if exampleSite is inside themesDir. 
                    ## MOVE exampleSite outside themesDir and put theme inside themes folder.
  
[params.placeholder]
  #disabled = true
  ## use img 
  _img = "/img/placeholder-100.png"
  
  ## use svg
  size = "100px"
  text = "[no image available]"
  text_size = "9px"
  
[params._scss]
  customFontBody = "Georgia,Utopia,Charter,serif"
  brandFont = "'Oswald', sans-serif"
  primary = "CadetBlue"
  primaryInvert = "#fff"
  
  footnote = "FOOTNOTE:"
  
[params._hero]
  #background = "img/hero-background.jpeg"
  #background = "img/hero-background-dark.jpeg"
  #background = "img/hero-background-light.jpeg"
  bgislight = false

[params._author]
  name = "Pointy Far"
  short = "Pointy"
  photo = "img/hello.jpeg"
  header = "Howdy!"
  blurb = " This is params author blurb. Configure me! \
            Possumus quorum aliqua aut anim ut eiusmod exquisitaque ut consequat. \
            O id sempiternum, voluptate quo ingeniis. \
            Duis ab et nulla incurreret, litteris qui possumus."
  aboutSection = "/about/"

[params._subnav]
  usetaxonomy = "tags"
  taxonomycount = 3
  featuredterms = ["queen"]
  
  
  
[params._footer]
  left = ["footerlinks", "otherlinks", "footerlinks"]
  right = ["copyright", "footertext", "footerimage"]
  

[params.tag_section]
  position = "head"
  label = "Filed under: "

[[params.display_taxonomies]]
  position = "head"
  name = "cuisine"
  labeled = true
  
[[params.display_taxonomies]]
  position = "head"
  name = "tags"
  style = "list"
  labeled = true
  label = "Tags: "

[[params.display_taxonomies]]
  position = "head"
  name = "difficulty"
  labeled = true
  label = "Difficulty: "

[[params.display_taxonomies]]
  position = "foot"
  name = "categories"
  labeled = true
  label = "Categorised: "

  
[taxonomies]
  category = "categories"
  tag = "tags"
  difficulty = "difficulty"
  cuisine = "cuisine"
